[package]
name = "serin_rebalance"
version = "0.1.0"
edition = "2021"
authors = ["SeleniaProject <dev@example.com>"]
license = "Apache-2.0"

[dependencies]
serde = { version = "1", features = ["derive"] } 