[workspace]
members = ["serindb", "serin_parser", "serinctl", "serin_storage", "serin_txn", "serin_optimizer", "serin_exec", "serin_index"]

[profile.release]
opt-level = 3
lto = true
codegen-units = 1 