[licenses]
allow = ["Apache-2.0", "MIT", "BSD-3-Clause", "ISC"]
denied = []

[advisories]
ignore = []

[bans]
multiple-versions = "warn"

[sources]
unknown-registry = "warn"
unknown-git = "deny" 