[package]
name = "serin_optimizer"
version = "0.1.0"
edition = "2021"
authors = ["SeleniaProject <dev@example.com>"]
license = "Apache-2.0"

[dependencies]
serin_parser = { path = "../serin_parser" }
serde = { version = "1.0", features = ["derive"] } 