[package]
name = "serin_index"
version = "0.1.0"
edition = "2021"
authors = ["SeleniaProject <dev@example.com>"]
license = "Apache-2.0"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
bitvec = "1"
murmur3 = "0.5" 
serin_json = { path = "../serin_json" } 