[package]
name = "serin_multidc"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
hdrhistogram = "7"
anyhow = "1"
bytes = "1"
async-trait = "0.1" 