[package]
name = "serin_metrics"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
prometheus = "0.13"
hyper = { version = "0.14", features = ["full"] }
tokio = { version = "1", features = ["full"] }
base64 = "0.21" 