[package]
name = "serin_json"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
rmp-serde = "1.1"
jsonschema = "0.17"
jsonpath_lib = "0.3"
anyhow = "1" 