[project]
name = "serin_py"
version = "0.1.0"
authors = [{name = "SeleniaProject"}]
requires-python = ">=3.8"
dependencies = [
    "asyncpg>=0.27.0"
]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta" 