[package]
name = "serin_rs"
version = "0.1.0"
edition = "2021"
authors = ["SeleniaProject <dev@example.com>"]
license = "Apache-2.0"

[dependencies]
tokio = { version = "1", features = ["rt", "macros"] }
tokio-postgres = "0.7" 