[package]
name = "serin_pool"
version = "0.1.0"
edition = "2021"
authors = ["SeleniaProject <dev@example.com>"]
license = "Apache-2.0"

[dependencies]
tokio = { version = "1", features = ["sync", "rt", "macros"] }
hyper = { version = "0.14", features = ["full"] }
async-trait = "0.1" 